<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-control btn-log border-grey int__5c974a</name>
   <tag></tag>
   <elementGuidId>2fd74985-48de-49fd-9564-be1af7b95e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.btn-log.border-grey.int_tel_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc814216-e3f1-4a87-acef-1161572a4131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>34df31ef-f588-456e-a4a9-5ac1b3256357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-log border-grey int_tel_input</value>
      <webElementGuid>360338e5-34ad-4891-b30b-c9b91f266474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>99abd22c-9552-45d1-ae5b-7ed63e07bb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>812-345-678</value>
      <webElementGuid>f0cf7778-e03b-4995-8fc1-23eec3fe0a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>intl-0</value>
      <webElementGuid>2bc12fe0-0bbf-47e0-a816-280f0a887a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>664a3d34-8d97-4fbe-96f8-90c1d85c5930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegister&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 register-row&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/input[@class=&quot;form-control btn-log border-grey int_tel_input&quot;]</value>
      <webElementGuid>d9733c5d-c0af-4bf3-8401-38d7c10bf2e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='tel']</value>
      <webElementGuid>768ebb8b-3f74-460b-9e6e-15d3273f91ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[5]/div[2]/div/input</value>
      <webElementGuid>7e447f00-98e6-4083-9f10-401e3b75a5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>54bdc6ca-9124-42e0-9d90-8a7691ec8787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '812-345-678']</value>
      <webElementGuid>9059b9e5-ec38-470a-9269-3ca7da32edbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
