<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Phone number is too short</name>
   <tag></tag>
   <elementGuidId>2fc53189-ef58-4af8-9c07-60b125289f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-mob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#error-mob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb207609-6e4f-473e-ae7c-9a3a85f63b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-alert alert-danger col-md-12 animated fadeInDown</value>
      <webElementGuid>bc71a7d5-b085-48d7-a71d-180ab9260381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-mob</value>
      <webElementGuid>25550de1-8bc0-4b64-b71f-7199d3a1ca2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone number is too short</value>
      <webElementGuid>16e86592-f57a-4409-b7b6-812262256272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-mob&quot;)</value>
      <webElementGuid>5025013e-9c68-40c4-bb22-594ab36122c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-mob']</value>
      <webElementGuid>af1f1f07-6717-45e5-92d7-0313207b92cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[2]/div/div</value>
      <webElementGuid>bb44e115-812c-4be4-a4aa-1544feeb0ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>4323ff4a-c512-4e96-bcdf-77d010790971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-mob' and (text() = 'Phone number is too short' or . = 'Phone number is too short')]</value>
      <webElementGuid>3979db53-56dc-48ae-98e4-a1629bd3f77e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
